name: Update Player Stats Manually

on:
  workflow_dispatch: # 手動実行専用

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib
          pip install -r requirements.txt

      - name: Fetch latest player data
        run: python3 get_player_data.py

      - name: Commit and push updated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add player_stats_*.csv
          # 変更があった場合のみコミット・プッシュする
          if ! git diff-index --quiet HEAD; then
            git commit -m "data: Update player statistics CSV files"
            git push
          else
            echo "No changes to commit."
          fi