name: Update Latest YouTube Videos Weekly

on:
  # mainブランチにプッシュされた時に実行
  push:
    branches:
      - main
      - master # 古い形式のブランチ名にも対応

  # 日本時間の毎週金曜 午前9時に実行
  schedule:
    - cron: '0 0 * * 5'
  
  # 手動でも実行できるようにする
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 最新の動画データを取得
      - name: Fetch latest YouTube videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python3 get_youtube_data.py

      # 5. HTMLページを再生成
      - name: Generate static HTML pages
        run: python3 main.py

      # 6. 変更をコミットしてプッシュ
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          # 変更があった場合のみコミット・プッシュする
          git diff-index --quiet HEAD || git commit -m "update: refresh latest youtube videos"
          git push