name: Build and Deploy NBA Stats Media

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境のセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 最新の動画データを取得
      - name: Fetch latest YouTube videos
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python3 get_youtube_data.py

      # 5. HTMLページを再生成
      - name: Generate static HTML pages
        run: python3 main.py

      # ★★★ デバッグ用に追加 ★★★
      - name: Check for output directory
        run: ls -R

      # 6. サイトをGitHub Pagesにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output